// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// fdagrouping
SEXP fdagrouping(SEXP Y1, SEXP Z1, SEXP X1, SEXP struT1, SEXP A1, SEXP beta1, SEXP eta1, SEXP lagU1, SEXP tuPara1, SEXP precision1);
RcppExport SEXP _fdagroup_fdagrouping(SEXP Y1SEXP, SEXP Z1SEXP, SEXP X1SEXP, SEXP struT1SEXP, SEXP A1SEXP, SEXP beta1SEXP, SEXP eta1SEXP, SEXP lagU1SEXP, SEXP tuPara1SEXP, SEXP precision1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type Z1(Z1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type struT1(struT1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type eta1(eta1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type lagU1(lagU1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type tuPara1(tuPara1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type precision1(precision1SEXP);
    rcpp_result_gen = Rcpp::wrap(fdagrouping(Y1, Z1, X1, struT1, A1, beta1, eta1, lagU1, tuPara1, precision1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fdagroup_fdagrouping", (DL_FUNC) &_fdagroup_fdagrouping, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_fdagroup(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
