# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib fdagroup
#' @importFrom Rcpp sourceCpp
#' @export
fdagrouping <- function(Y1, Z1, X1, struT1, A1, beta1, eta1, lagU1, tuPara1, precision1) {
    .Call('_fdagroup_fdagrouping', PACKAGE = 'fdagroup', Y1, Z1, X1, struT1, A1, beta1, eta1, lagU1, tuPara1, precision1)
}

